apiVersion: v1
kind: Namespace
metadata:
  name: cb-ops
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: cb-ops
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 6Gi
    limits.cpu: "4"
    limits.memory: 10Gi
    services.loadbalancers: "0"
    services.nodeports: "0"
    persistentvolumeclaims: "3"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cb-ops
  namespace: cb-ops

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-create
  namespace: cb-ops
rules:
- apiGroups: [""]
  resources: ["namespace"]
  verbs: ["create","get","list","patch","update","watch"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pods-all
  namespace: cb-ops
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cb-ops
  namespace: cb-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-all
subjects:
- kind: ServiceAccount
  name: cb-ops

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ops-namespace
  namespace: cb-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-create
subjects:
- kind: ServiceAccount
  name: ops-namespace