# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- namespace.yaml
- resource-quota.yaml
- service-account.yaml
- role.yaml
- role-binding.yaml


commonLabels:
  createdBy: CloudBeesCore